Cosmetics: Logs, comments, formatting...

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -4,7 +4,7 @@ VERSION = @PACKAGE_VERSION@
 BUNDLE_DIR = bundle
 
 DUPS_IN  = $(shell ocamlfind query compiler-libs)
-OCAMLC = OCAMLPATH=$(OCAMLPATH) OCAMLRUNPARAM= OCAMLFIND_IGNORE_DUPS_IN="$(DUPS_IN)" ocamlfind ocamlc
+OCAMLC   = OCAMLPATH=$(OCAMLPATH) OCAMLRUNPARAM= OCAMLFIND_IGNORE_DUPS_IN="$(DUPS_IN)" ocamlfind ocamlc
 OCAMLOPT = OCAMLPATH=$(OCAMLPATH) OCAMLRUNPARAM= OCAMLFIND_IGNORE_DUPS_IN="$(DUPS_IN)" ocamlfind ocamlopt
 OCAMLDEP = OCAMLPATH=$(OCAMLPATH) OCAMLRUNPARAM= OCAMLFIND_IGNORE_DUPS_IN="$(DUPS_IN)" ocamlfind ocamldep
 QTEST    = qtest
@@ -126,17 +126,9 @@ all: $(INSTALLED) bundle
 	@echo 'Compiling $@'
 	$(OCAMLC) $(OCAMLCFLAGS) -package "$(PACKAGES)" -c $<
 
-# Documentation
-
 %.html: %.adoc
 	@echo 'Building documentation $@'
 	asciidoc -a data-uri -a icons -a toc -a max-width=55em --theme volnitsky -o $@ $<
-
-doc: docs/tutorial.html docs/manual.html docs/roadmap.html
-
-docs/tutorial.html: docs/tutorial_group_by.svg docs/sample_chart1.svg
-
-# Dependencies
 
 RAMEN_SOURCES = \
 	src/RamenVersions.ml \
@@ -316,8 +308,8 @@ CODEGENLIB_SOURCES = \
 	src/CodeGenLib_Publish.ml \
 	src/RamenCopy.ml \
 	src/RamenCopyClt.ml \
-	src/CodeGenLib_Skeletons.ml
-	src/HeavyHitters.ml \
+	src/CodeGenLib_Skeletons.ml \
+	src/HeavyHitters.ml
 
 RMADMIN_SOURCES = \
 	src/RamenVersions.ml \
@@ -472,6 +464,9 @@ SOURCES = $(sort \
 	$(TESTONLY_SOURCES) \
 )
 
+
+# Dependencies
+
 dep:
 	$(RM) .depend
 	$(MAKE) .depend
@@ -483,6 +478,14 @@ dep:
 	done
 
 include .depend
+
+
+# Documentation
+
+doc: docs/tutorial.html docs/manual.html docs/roadmap.html
+
+docs/tutorial.html: docs/tutorial_group_by.svg docs/sample_chart1.svg
+
 
 # Compile Ramen
 
@@ -569,39 +572,6 @@ src/orc/orc_writer: \
 		$(BUNDLE_DIR)/lib/liborc.a
 	@echo 'Linking $@'
 	$(OCAMLOPT) $(OCAMLOPTFLAGS) -linkpkg $(MOREFLAGS) $(filter %.cmx, $^) -o $@
-
-orc-check: src/orc/orc_writer $(wildcard tests/orc/*.type) $(wildcard tests/orc/*.data)
-	@echo 'Checking ORC writes...'
-	@failed="" ;\
-	 for t in $(wildcard tests/orc/*.type); do \
-	   base="$$(basename $$t .type)" ;\
-	   echo "  Checking $$base" ;\
-	   typ=$$(cat "$$t") ;\
-	   data="$$(dirname $$t)/$$base.data" ;\
-	   writer="/tmp/$$base" ;\
-	   orc="/tmp/$$base.orc" ;\
-	   csv="/tmp/$$base.csv" ;\
-	   if ! (\
-	     src/orc/orc_writer "$$writer" "$$typ" &&\
-	     "$$writer" write "$$orc" < "$$data" &&\
-	     "$$writer" read  "$$orc" > "$$csv" ;\
-	   ) then \
-	     echo "\033[1;31mFAILURE\033[0m: Cannot create CSV file for $$base" ;\
-	     failed="$$failed $$base" ;\
-	   else \
-	     if diff -q "$$data" "$$csv"; then \
-	       echo "\033[1;32mSUCCESS\033[0m" ;\
-	     else \
-	       echo "\033[1;31mFAILURE\033[0m: $$data and $$csv differ:" ;\
-	       diff "$$data" "$$csv" ;\
-	       failed="$$failed $$base" ;\
-	     fi ;\
-	   fi ;\
-	 done ;\
-	 if test -n "$$failed"; then \
-	   echo "\033[1;31mFAILURE\033[0m:$$failed" ;\
-	   exit 1 ;\
-	 fi
 
 src/ramen: \
 		$(patsubst %.mli,%.cmi,$(filter %.mli, $(RAMEN_SOURCES))) \
@@ -1091,7 +1061,6 @@ ringbuf_test.opt: \
 		src/RamenOutRef.cmx \
 		src/RamenUnits.cmx \
 		src/RamenTuple.cmx \
-		src/RamenVersions.cmx \
 		src/RingBuf.cmx \
 		src/RingBufLib.cmx \
 		src/RamenOrc.cmx \
@@ -1235,6 +1204,40 @@ RAMEN_ARCHIVIST_TESTS = $(wildcard tests/archivist/*.allocs)
 arc-check: src/ramen $(RAMEN_ARCHIVIST_TESTS)
 	@echo 'Running storage allocation tests'
 	@echo 'TODO: make it possible to upload the stats file in the confserver'
+
+orc-check: src/orc/orc_writer $(wildcard tests/orc/*.type) $(wildcard tests/orc/*.data)
+	@echo 'Checking ORC writes...'
+	@failed="" ;\
+	 for t in $(wildcard tests/orc/*.type); do \
+	   base="$$(basename $$t .type)" ;\
+	   echo "  Checking $$base" ;\
+	   typ=$$(cat "$$t") ;\
+	   data="$$(dirname $$t)/$$base.data" ;\
+	   writer="/tmp/$$base" ;\
+	   orc="/tmp/$$base.orc" ;\
+	   csv="/tmp/$$base.csv" ;\
+	   if ! (\
+	     src/orc/orc_writer "$$writer" "$$typ" &&\
+	     "$$writer" write "$$orc" < "$$data" &&\
+	     "$$writer" read  "$$orc" > "$$csv" ;\
+	   ) then \
+	     echo "\033[1;31mFAILURE\033[0m: Cannot create CSV file for $$base" ;\
+	     failed="$$failed $$base" ;\
+	   else \
+	     if diff -q "$$data" "$$csv"; then \
+	       echo "\033[1;32mSUCCESS\033[0m" ;\
+	     else \
+	       echo "\033[1;31mFAILURE\033[0m: $$data and $$csv differ:" ;\
+	       diff "$$data" "$$csv" ;\
+	       failed="$$failed $$base" ;\
+	     fi ;\
+	   fi ;\
+	 done ;\
+	 if test -n "$$failed"; then \
+	   echo "\033[1;31mFAILURE\033[0m:$$failed" ;\
+	   exit 1 ;\
+	 fi
+
 
 # Installation
 
