Build: fix bundle depending on install

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -25,6 +25,16 @@ else
 FILE_NOTIFIER = src/RamenFileNotify_Inotify.ml
 endif
 
+# parsercombinator is used by string to IP conversion :(
+META_REQUIRES = \
+	findlib batteries stdint parsercombinator threads \
+	inotify binocle lacaml ppp ppp.unix syslog
+# The above are the dependencies required when ramen is running.
+# To build ramen you will also need:
+#   unix num js_of_ocaml js_of_ocaml-ppx cmdliner sqlite3
+#   compiler-libs compiler-libs.common
+#   compiler-libs.bytecomp compiler-libs.optcomp
+
 PACKAGES = \
 	ppp ppp.unix batteries cmdliner stdint parsercombinator \
 	syslog num inotify binocle unix lacaml \
@@ -33,10 +43,10 @@ PACKAGES = \
 
 INSTALLED_BIN = src/ramen
 INSTALLED_LIB = \
-	META src/codegen.cmxa src/codegen.a \
+	src/codegen.cmxa src/codegen.a \
 	$(CODEGENLIB_SOURCES:.ml=.cmi) $(CODEGENLIB_SOURCES:.ml=.cmx) \
 	src/libringbuf.a src/libcollectd.a src/libnetflow.a
-INSTALLED = $(INSTALLED_BIN) $(INSTALLED_LIB)
+INSTALLED = $(INSTALLED_BIN) $(INSTALLED_LIB) META
 
 bin_dir ?= /usr/bin/
 # Where the deb (or other non-opam) version of ramen will get the libraries
@@ -237,7 +247,7 @@ dep:
 .depend: $(SOURCES)
 	@$(OCAMLDEP) -native -I src -package "$(PACKAGES)" $(filter %.ml, $(SOURCES)) $(filter %.mli, $(SOURCES)) > $@
 	@for f in $(filter %.c, $(SOURCES)); do \
-		$(CC) $(CPPFLAGS) -MM -MT "$$(dirname $$f)/$$(basename $$f .c).o" $$f >> $@; \
+	  $(CC) $(CPPFLAGS) -MM -MT "$$(dirname $$f)/$$(basename $$f .c).o" $$f >> $@; \
 	done
 
 include .depend
@@ -291,21 +301,33 @@ OCAML_WHERE = $(shell dirname $(shell ocamlfind ocamlc -where))
 # cut -c X- means to takes all from X, 1st char being 1, thus the leading _:
 OCAML_WHERE_LEN = $(shell printf '_%s/' $(OCAML_WHERE) | wc -m | xargs echo)
 
+META:
+	@echo 'Building findlib configuration (META) for Ramen'
+	@echo 'description = "Event processor tailored for small-scale monitoring"' > $@
+	@echo 'version = "$(VERSION)"' >> $@
+	@echo 'archive(native) = "codegen.cmxa"' >> $@
+	@echo 'requires = "$(META_REQUIRES)"' >> $@
+
 BUNDLE_DIR = bundle
 
 bundle: bundle/date
 
-bundle/date: src/codegen.cmxa
+bundle/date: $(INSTALLED_LIB)
 	@echo 'Bundling libs together into $(BUNDLE_DIR)'
 	@$(RM) -r '$(BUNDLE_DIR)'
 	@mkdir -p '$(BUNDLE_DIR)'
-	@set -e ; for d in $$(ocamlfind query -recursive -predicates native -format '%d' ramen | sort -u | grep -v /findlib) ; do \
-		cp -r "$$d" '$(BUNDLE_DIR)/' ;\
-	done
+	@set -e ;\
+	 deps=$$( \
+	   for p in $(META_REQUIRES) ; do \
+	     ocamlfind query -recursive -predicates native -format '%d' $$p ;\
+	   done | sort -u | grep -v /findlib) ;\
+	 for d in $$deps ; do cp -r "$$d" '$(BUNDLE_DIR)/' ; done
+	@mkdir $(BUNDLE_DIR)/ramen
+	@cp $(INSTALLED_LIB) $(BUNDLE_DIR)/ramen
 	@find '$(BUNDLE_DIR)' -type f -not '-(' \
-			-name '*.cmx*' -o -name '*.cmi' -o -name '*.a' -o \
-			-name '*.so' -o -name '*.o' \
-		'-)' -delete
+	    -name '*.cmx*' -o -name '*.cmi' -o -name '*.a' -o \
+	    -name '*.so' -o -name '*.o' \
+	  '-)' -delete
 	@find '$(BUNDLE_DIR)' -empty -delete
 	@# Delete some of the biggest unused files:
 	@$(RM) $(BUNDLE_DIR)/batteries/batteriesExceptionless.cm*
@@ -328,16 +350,16 @@ src/RamenDepLibs.ml:
 	@echo '(* Generated by Makefile - edition is futile *)' > $@
 	@echo 'let incdirs = [' >> $@
 	@set -e ; for d in $$(ocamlfind query -recursive -predicates native -format '%d' ramen | sort -u | grep -v -e compiler-libs -e ppx_tools -e /findlib) ; do \
-		echo $$d | cut -c $(OCAML_WHERE_LEN)- | \
-		sed -e 's,^\(.*\)$$,  "\1" ;,' >> $@ ;\
+	  echo $$d | cut -c $(OCAML_WHERE_LEN)- | \
+	  sed -e 's,^\(.*\)$$,  "\1" ;,' >> $@ ;\
 	done ;
 # Equivalent to -threads:
 	@echo '  "ocaml/threads" ;' >> $@
 	@echo ']' >> $@
 	@echo 'let objfiles = [' >> $@
 	@set -e ; for d in $$(ocamlfind query -recursive -predicates native -format '%+a' ramen | uniq | grep -v -e compiler-libs -e ppx_tools -e /findlib) ; do \
-		echo $$d | cut -c $(OCAML_WHERE_LEN)- | \
-		sed -e 's,^\(.*\)$$,  "\1" ;,' >> $@ ;\
+	  echo $$d | cut -c $(OCAML_WHERE_LEN)- | \
+	  sed -e 's,^\(.*\)$$,  "\1" ;,' >> $@ ;\
 	done ;
 	@echo ']' >> $@
 # Equivalent to -threads, must come right after unix.cmxa:
@@ -588,19 +610,19 @@ arc-check: src/ramen $(RAMEN_ARCHIVIST_TESTS)
 	@echo 'Running storage allocation tests'
 	@set -e; \
 	 for f in $(RAMEN_ARCHIVIST_TESTS); do \
-		d=$$(dirname $$f)/$$(basename $$f .allocs) ;\
-		src/ramen archivist --persist-dir $$d --no-stats --no-reconf --stdout ;\
-		if ! diff -q $$f $$d/archivist/v*/allocs ; then \
-			echo "FAILURE: $$f" ;\
-			exit 1 ;\
-		fi ;\
+	  d=$$(dirname $$f)/$$(basename $$f .allocs) ;\
+	  src/ramen archivist --persist-dir $$d --no-stats --no-reconf --stdout ;\
+	  if ! diff -q $$f $$d/archivist/v*/allocs ; then \
+	    echo "FAILURE: $$f" ;\
+	    exit 1 ;\
+	  fi ;\
 	done ;\
 	echo SUCCESS
 
 # Installation
 
 install: $(INSTALLED)
-	@ocamlfind install ramen $(INSTALLED_LIB)
+	@ocamlfind install ramen $(INSTALLED_LIB) META
 	@echo 'Installing binaries into $(prefix)$(bin_dir)'
 	@install -d $(prefix)$(bin_dir)
 	@install $(INSTALLED_BIN) $(prefix)$(bin_dir)/
@@ -687,12 +709,12 @@ docker/ramen.$(VERSION).deb: ramen.$(VERSION).deb
 
 docker-build-builder: docker/Dockerfile-builder
 	@for distrib in jessie stretch ; do \
-		echo 'Building docker image for building the DEB packages for $$distrib' ;\
-		echo 'FROM debian:'$$distrib > docker/Dockerfile-builder.$$distrib ;\
-		cat docker/Dockerfile-builder >> docker/Dockerfile-builder.$$distrib ;\
-		docker build -t rixed/ramen-builder:$$distrib \
-		             -f docker/Dockerfile-builder.$$distrib docker/ ;\
-		$(RM) docker/Dockerfile-builder.$$distrib ;\
+	  echo 'Building docker image for building the DEB packages for $$distrib' ;\
+	  echo 'FROM debian:'$$distrib > docker/Dockerfile-builder.$$distrib ;\
+	  cat docker/Dockerfile-builder >> docker/Dockerfile-builder.$$distrib ;\
+	  docker build -t rixed/ramen-builder:$$distrib \
+	               -f docker/Dockerfile-builder.$$distrib docker/ ;\
+	  $(RM) docker/Dockerfile-builder.$$distrib ;\
 	done
 
 docker/z3: $(Z3)
@@ -742,3 +764,4 @@ clean: clean-temp
 	@$(RM) -r tmp
 	@$(RM) ramen.*.deb ramen.*.tgz
 	@$(RM) $(PAGES)
+	@$(RM) META
